service: twitter-appsync-backend

plugins:
  - serverless-appsync-plugin

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
