service: twitter-appsync-backend
frameworkVersion: "3"

plugins:
  - serverless-appsync-plugin

package:
  exclude:
    - "package-lock.json"
    - "package.json"

custom:
  appSync:
    - ${file {serverless.appsync-api.yml}}


provider:
  name: aws
  runtime: nodejs18.x

# you can add CloudFormation resource templates here
resources:
 Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: name
          Required: false
          Mutable: true
CognitoUserPoolId:
  Type: AWS::Cognito::UserPool::Id
  Properties:
    Value:
      Ref: CognitoUserPool
